# Save the output of this file and use kubectl create -f
# to import it into Kubernetes.
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  containers:
    - args:
        - --path.rootfs=/host
      image: docker.io/prom/node-exporter:latest
      name: node_exporter
      ports:
        - containerPort: 9100
          hostPort: 9100
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /host
          name: root-host-0
          readOnly: true
  enableServiceLinks: false
  hostNetwork: true
  volumes:
    - hostPath:
        path: /
        type: Directory
      name: root-host-0
