# Save the output of this file and use kubectl create -f
# to import it into Kubernetes.
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafanagpm
  name: grafanagpm
spec:
  containers:
    - name: grafana
      image: docker.io/grafana/grafana-oss
      ports:
        - containerPort: 3000
          hostPort: 3000
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafana_provisioning
        - mountPath: /var/lib/grafana/dashboards
          name: grafana_dashboards
      args:
        - /bin/bash
        - -c
  restartPolicy: OnFailure
  volumes:
    - name: grafana_provisioning
      hostPath:
        path: /deployment/grafanagpm/provisioning
        type: Directory
    - name: grafana_dashboards
      hostPath:
        path: /deployment/grafanagpm/dashboards
        type: Directory
status: {}
