# Save the output of this file and use kubectl create -f
# to import it into Kubernetes.
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: miniogpm
  name: miniogpm
spec:
  containers:
    - name: minio
      image: docker.io/minio/minio
      ports:
        - containerPort: 9000
          hostPort: 9009
        - containerPort: 9990
          hostPort: 9990
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /data
          name: minio_bucket
      command:
        - /bin/bash
        - -c
      args:
        - minio server /data --console-address :9990
      env:
        - name: MINIO_ROOT_USER
          value: ROOTNAME
        - name: MINIO_ROOT_PASSWORD
          value: CHANGEME123
  restartPolicy: OnFailure
  volumes:
    - name: minio_bucket
      hostPath:
        path: /deployment/miniogpm
        type: Directory
status: {}
